baseURL: ""
languageCode: "en-us"
title: "Vishal's Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: ""
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "" # Brand name for the brand | default is the title variable
    disableSearch: True
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: True
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Vishal K Panda"
    subtitle: "I Design AI for Impact"
    content: "A passionate data scientist leveraging modern AI to build scalable, impactful solutions across diverse industries."
    image: /images/vishal.jpeg
    bottomImage:
      enable: true

    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/vishalpanda10/
        - icon: fab fa-github
          url: https://www.github.com/vishalpanda10/
      #customIcons:
      #  - icon: /fav.png
      #    url: "https://example.com"
  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/panda_circle.jpeg"
    content: |-
          I am a data scientist who recently graduated from Michigan State University. Currently, I am working as a research assistant at MSU, specializing in data science and AI in bioinformatics. I have a diverse background working on various projects across multiple industries, building AI solutions and data engineering pipelines to transform complex data into meaningful insights and practical applications.


      I am currently working on projects that leverage AI to optimize patient care and enhance market analysis using academic and patent data.


      

    skills:
      enable: true
      title: "The technologies I have have experience in:"
      items:
        - "<b>Languages:</b> Python, R, SQL, HTML, CSS, JavaScript"
        - "<b>Data Science & AI:</b> Machine Learning (Supervised Learning, Unsupervised Learning, Bayesian Methods), Deep Learning(CNN, RNN, Transformers), Generative Modeling (Variational Autoencoders, Diffusion Models), Natural Language Processing(NLP), Large Language Models (LLAMA, GPT 3 etc.), Prompt Engineering, Statistical Analysis, Data Analysis"
        - "<b>Frameworks & Libraries:</b> PyTorch, TensorFlow, SciKit-Learn, NLTK, SpaCy, Pandas, NumPy, SciPy, LangChain, LlamaIndex, FastAPI, Flask"
        - "<b>Big Data & Databases:</b> Apache Spark, Hadoop, Apache Hive, Kafka, MongoDB (NoSQL), Vector Databases (ChromaDB, Pinecone, FAISS)"
        - "<b>Cloud Platforms:</b> AWS (EC2, S3, Lambda, Redshift, DynamoDB, Glue, Bedrock), Azure(Azure Data Lake, Azure Databricks, Azure Machine Learning, Azure Synapse Analytics, Cosmos DB, Azure Data Factory)"
        - "<b>Utilities:</b> Docker, Git, LaTex, Shell Scripting, Slurm, CI/CD"
        




  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Research Assistant"
        company: "Michigan State University"
        companyUrl: "https://msu.edu/"
        date: "Jan 2023 - present"
        featuredLink:
          enable: False
          name: "View the project"
          url: "https://example.com"
        content: |-
          I am working as a research assistant under [Dr. Sudin Bhattacharya](https://iq.msu.edu/sudin-bhattacharya/), specializing in applying data science and AI in bioinformatics to model complex biological systems and uncover new data insights.
          
          - Working on conditional generation using generative models to produce and analyze transitional gene expression profiles, enhancing understanding of cell differentiation across various cell types.
          - Applied machine learning and Bayesian methods to predict cell-cell communication in perivascular adipose tissue (PVAT), focusing on integrin interactions to understand their role in stress relaxation; this research is submitted for review to Pharmacological Research.
          - Applied advanced analysis and probabilistic modeling of single-cell data to trace heart development stages and uncover key trends, contributing to a published study on heart organoid development (https://pubmed.ncbi.nlm.nih.gov/38086920/).

          - Employed statistical modeling techniques to analyze lipidomics data, identifying key biomarkers and advancing the understanding of lipid metabolism; this research is currently under review for publication.

          - Deployed machine learning models on high-performance computing (HPC) clusters to analyze large-scale single-cell RNA-seq liver data, revealing intricate details of liver function and disease mechanisms.
                 
                        

      - job: "Data Scientist"
        company: "Wipro Technologies"
        companyUrl: "https://www.wipro.com/"
        date: "Nov 2019 - Jul 2022"
        featuredLink:
          enable: False
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I have worked in the field of data science as a Data Scientist and Engineer at [Wipro Technologies](https://www.wipro.com/) in Chennai, India.


          - Developed and implemented machine learning solutions, including neural networks and BERT-based NLP models, to enhance financial data insights, compliance checks, and operational efficiency.
          - Engineered scalable data workflows and optimized ETL pipelines across financial applications using PySpark, SQL, and cloud technologies, significantly enhancing data processing efficiency and operational decision-making.




  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master's in Data Science"
        school:
          name: "Michigan State University, East Lansing"
          url: "https://msu.edu/"
        date: "2022 - 2024"
        GPA: "3.94 out of 4.0"
        content: |-
          Courses Enrolled
            - CSE 890: Capstone Project 
            - CSE 891: Large Language Models
            - STT 812: Bayesian Statistics 
            - CSE 849: Deep Learning
            - CMSE 831: Computational Optimization
            - CSE 881: Data Mining 
            - CSE 842: Natural Language Processing
            - CSE 847: Machine Learning
            - STT 811: Applied Statistical Modeling for Data Science
            - CMSE 830: Foundations of Data Science
            - CSE 482: Big Data Analysis
            - STT 810: Mathematical Statistics for Data Scientists
            
          Extracurricular Activities
            - Worked on multiple projects in [MSU AI Club](https://www.msuaiclub.com/)
        
      - title: "Bachelor of Engineering"
        school:
          name: "College of Engineering and Technology"
          url: "https://www.cet.edu.in/"
        date: "2015 - 2019"
        GPA: ""
        content: |-



        featuredLink:
          enable: False
          name: "My academic record"
          url: "https://example.com"


  # Achievements
  achievements:
    enable: False
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg

        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "Projects"
    items:
      - title: Personal Portfolio
        content: An easily customizable and mobile-friendly personal website. It is a website that projects and presents my works and achievements in the right dimension.
        image: /images/projects/panda_portfolio.png
        #featured:
        #  name: Demo
        #  link: https://hugo-profile.netlify.app
        badges:
          - "CSS"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:vishalpanda10@gmail.com
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile


      - title: Predicting Funding Flows in Public and Private Markets Using Acadmeic and Patent Data
        content: A robust framework for forecasting funding flows in public and private markets by harnessing the power of data science, time series analysis, and NLP.
        image: /images/projects/converter.jpg
        #featured:
        #  name: Demo
        #  link: https://django-converter.herokuapp.com
        badges:
          - "NLP"
          - "Time Series Analysis"
          - "OpenAlex"
          - "Cross-Domain Topic Mapping"
          - "Machine Learning"
          - "Large Language Models"
        links:
          - icon: fab fa-github
            url: https://github.com/parthmaheshwari/emerging-sectors-forecast.git

      - title: AI-Driven Analysis for Optimizing RILA Cap Rate Strategies
        content: The project, as a part of Jackson Company, is to use machine learning to predict cap rate changes for registered index-linked annuities (RILAs) by analyzing market features and competitor behaviors to refine cap rate setting strategies.
        image: /images/projects/rila_updated.png
        #featured:
        #  name: 
        #  link: 
        badges:
          - "Time Series Analysis"
          - "Machine Learning"
          - "Insurance"
          - "Anomaly Detection"
          - "Temporal Diffusion Transformers"
          - "Regression"
          - "Classification"
        links:
          - icon: fab fa-github
            url: https://github.com/stevenstrachan/rila-insights-ml.git
            
      - title: Prompt Guided Image Generation
        content: This project enhances AI-generated images by integrating advanced NLP for enriching captions and using visual question answering to extract detailed image descriptions. These techniques significantly improve the alignment and fidelity between textual descriptions and visual outputs, ensuring high-quality multimedia content creation.
        image: /images/projects/prompt_generation.png
        #featured:
        #  name: Demo V2
        #  link: 
        badges:
          - "Large Language Models"
          - "Contextual Enrichment"
          - "Retreival-Augmented Generation"
          - "Visual QA"
          - "Stable Diffusion"
          - "Prompt Engineering"

        links:
          - icon: fab fa-github
            url: https://github.com/vishalpanda10/cse_891_llm_project.git
    

      - title: Predicting Diagnoses from EHR Data
        content: This project constructs a knowledge graph from synthetic EHR data using Graph Attention Networks to predict patient diagnoses, focusing on healthcare interactions and classification accuracy.
        image: /images/projects/ehr.png
        #featured:
        #  name: Demo V2
        #  link: 
        badges:
          - "Knowledge Graphs"
          - "Graph Attention Networks"
          - "Multi-task Learning"
          - "Patient Diagnosis"
          - "Data Mining"

        links:
          - icon: fab fa-github
            url: https://github.com/vishalpanda10/Multi-task-learning-with-graph-attention-networks-for-EHR-records.git
        


      - title: NLP with Adversial Learning
        content: A natural language generation (NLG) method combining Transformers and Generative Adversarial Networks (GANs). Our approach enhances text generation by using Transformers within a GAN framework, addressing the discrete output space problem without gradient estimators. A discriminator network differentiates between generated and high-quality reference texts.
        image: /images/projects/adversial.png
        #featured:
        #  name: Demo V2
        #  link: 
        badges:
          - "Natural Language Generation"
          - "Transformers"
          - "Generative Adversarial Networks"
          - "Text Generation" 
          - "Neural Networks"

        links:
          - icon: fab fa-github
            url: https://github.com/vishalpanda10/NLG-with-Adversial-Learning.git









  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to reach out for feedback and discussions! I'll get back to you as soon as I can.
    btnName: Mail me
    btnLink: mailto:vishalpanda10@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
